version: '3.4'

services:

  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hashtagsxrep
      MYSQL_USER: htags
      MYSQL_PASSWORD: htags
      TZ: "Europe/Madrid"
    ports:
      - '8889:3306'
    expose:
      - '8889'
    restart: on-failure
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql